app = "http4s-on-fly-io"
kill_signal = "SIGINT"
kill_timeout = 120

[env]
  BASE_URL = "https://http4s-on-fly-io.fly.dev"

[build]
  image = "hello-server:0.1.0"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 500
    soft_limit = 250
    type = "requests"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    grace_period = "10s"
    interval = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 5
    timeout = "2s"
